default: &default
  adapter: mysql2
  user: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  pool: 5
  timeout: 5000
  host: db

development:
  <<: *default
  database: sunrise

test:
  <<: *default
  database: cms_test

production:
  <<: *default
  database: sunrise
